export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERRORS = "REGISTER_ERRORS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERRORS = "LOGIN_ERRORS";
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const LOGOUT = "LOGOUT";
export const AUTH_START_LOADING = "AUTH_START_LOADING";
export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";

export const GETBG_SUCCESS = "GETBG_SUCCESS";
export const GETBG_ERROR = "GETBG_ERROR";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";
export const UPDATE_LIST_ERROR = "UPDATE_LIST_ERROR";
export const ADD_TO_LIST_SUCCESS = "ADD_TO_LIST_SUCCESS";
export const ADD_TO_LIST_ERROR = "ADD_TO_LIST_ERROR";
export const LOAD_TVSHOWS = "LOAD_TVSHOWS";
